server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: curriculum-service
          uri: lb://curriculum-service
          predicates:
            - Path=/cv/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
